### ISSUE TITLE
[Bug]: Progress bar caps out at 24hrs

### ISSUE THREAD

**Issue by djdevin** [nickbeen/php-cli-progress-bar#19]
### Library version

1.1.1

### PHP version

8.2

### Bug description

We have some big tasks :)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by nickbeen** [comment]
Thank you for your useful insight with using this library for big tasks. The behavior of the progress bar has been changed in version 1.1.2 to avoid capping out at 24 hours.
